Repository jobzz-kj/Hacktober, pull requests merged in 2022-10, with the labels that each got.

#57 Update python.py
  python.py
Labels: hacktoberfest-accepted

#58 Program to calculate factorial using loop
  factorialUsingLoop.py
Labels: hacktoberfest-accepted

#60 Find Factorial using Recursion
  factRecursion.py
Labels: hacktoberfest-accepted

#62 program to solve quadratic eqn
  Quadratic.py
Labels: hacktoberfest-accepted

#64 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#66 Update sum.c
  sum.c
Labels: hacktoberfest-accepted

#70 Update python.py
  python.py
Labels: hacktoberfest-accepted

#68 Update great.py
  great.py
Labels: hacktoberfest-accepted

#71 Update python2.py
  python2.py
Labels: hacktoberfest-accepted

#67 Update factRecursion.py
  factRecursion.py
Labels: hacktoberfest-accepted

#61 Update python.py
  python.py
Labels: hacktoberfest-accepted

#65 Update turtle.py
  turtle.py
Labels: hacktoberfest-accepted

#74 Update Quadratic.py
  Quadratic.py
Labels: enhancement, good first issue, hacktoberfest-accepted

#76 Update great.py
  great.py
Labels: good first issue, hacktoberfest-accepted

#77 Check the tuple size
  tupleSize.py
Labels: good first issue, hacktoberfest-accepted

#78 Date difference between 2 dates
  dateDiff.py
Labels: good first issue, hacktoberfest-accepted

#79 Iterative Binary Search
  binSearchIterative.py
Labels: hacktoberfest-accepted

#80 Create heapSort.py
  heapSort.py
Labels: hacktoberfest-accepted

#82 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: hacktoberfest-accepted

#81 Create recursive_binary_search.py
  Recursive_binary_search.py
  recursive_binary_search.py
Labels: hacktoberfest-accepted

#83 Update README.md
  README.md
Labels: hacktoberfest-accepted

#84 Update shell.py
  shell.py
Labels: hacktoberfest-accepted

#85 Update dateDiff.py
  dateDiff.py
Labels: hacktoberfest-accepted
